http://abczu.xyz:25461/get.php?username=chao&password=chao&type=m3u
http://abczu.xyz:25461/get.php?username=craig&password=craig&type=m3u
http://abczu.xyz:25461/get.php?username=frank&password=frank&type=m3u
http://abczu.xyz:25461/get.php?username=stewart&password=stewart&type=m3u
http://abczu.xyz:25461/get.php?username=victor&password=victor&type=m3u
http://abczu.xyz:25461/get.php?username=wayne&password=wayne&type=m3u
